accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name='accounts/pw_change.html'),
         name='pw_change'),
    path('profile/', views.get_member, name='get_member'),
    path('profile/<int:member_id>/', views.get_member, name='get_member_id'),
    path('change-profile/', views.update_member, name='profile_change'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from forum import views as forum_views

urlpatterns = [
    path('', forum_views.home, name='site_home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('forum/', include('forum.urls'))
]

forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.article, name='home'),
    path('new/', views.new, name='new_article'),
    path('<int:pk>/', views.detail),
    path('<int:pk>/delete/', views.delete),
    path('<int:pk>/edit/', views.edit),
    path('<int:pk>/update/', views.update),
]

common/models.py
from django.db import models

# Create your models here.

forum/models.py
from django.db import models
from django.conf import settings


# from account.models import User

class Post(models.Model):
    # 1. 게시글의 id 값
    id = models.AutoField(primary_key=True, null=False, blank=False)
    # 2. 제목
    title = models.CharField(max_length=100)
    # 3. 작성일
    created_at = models.DateTimeField(auto_now_add=True)
    # 4. 작성자
    # writer = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    # writer = models.CharField(max_length=20)
    # 5. 본문
    body = models.TextField()
    # 6. 수정 일시
    modify_date = models.DateTimeField(null=True, blank=True)

    # 게시글의 이름을 title로 선언
    def __str__(self):
        return self.title

    # 게시글 요약 정보
    def summary(self):
        return self.body[:10]

# Create your models here.

post/models.py
from django.db import models
from django.conf import settings


# from account.models import User

class Post(models.Model):
    # 1. 게시글의 id 값
    id = models.AutoField(primary_key=True, null=False, blank=False)
    # 2. 제목
    title = models.CharField(max_length=100)
    # 3. 작성일
    created_at = models.DateTimeField(auto_now_add=True)
    # 4. 작성자
    # writer = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    # writer = models.CharField(max_length=20)
    # 5. 본문
    body = models.TextField()
    #
    modify_date = models.DateTimeField(null=True, blank=True)

    # 게시글의 이름을 title로 선언
    def __str__(self):
        return self.title

    # 게시글 요약 정보
    def summary(self):
        return self.body[:10]

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "password1", "password2")

forum/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post  # 사용할 모델
        fields = ['title', 'body']  # PostForm에서 사용할 Post 모델의 속성

accounts/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from accounts.forms import UserCreateForm


def signup(request):
    if request.method == "POST":
        form = UserCreateForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('site_home')
    else:
        form = UserCreateForm()
    return render(request, 'accounts/signup.html', {'form': form})


@login_required(login_url='accounts:login')
def change_password(request):
    return render(request, 'accounts/pw_change.html')


@login_required(login_url='accounts:login')
def get_member(request, member_id=None):
    if member_id is None:
        member_id = request.user.id

    user = User.objects.get(id=member_id)
    return render(request, 'accounts/profile.html', {'get_user': user})


@login_required(login_url='accounts:login')
def update_member(request):
    print(request.user)
    return render(request, 'accounts/profile_change.html')

common/views.py
from django.shortcuts import render

# Create your views here.

forum/views.py
from django.shortcuts import render, redirect

from .forms import PostForm
from .models import Post


def home(request):
    return render(request, 'forum/home.html')


def article(request):
    posts = Post.objects.all()
    return render(request, 'forum/article.html', {'posts': posts})


def new(request):
    print("new")
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('/forum/')
    else:
        form = PostForm()
    context = {'form': form}
    return render(request, 'forum/new.html', context)


def detail(request, pk):
    post = Post.objects.get(pk=pk)
    return render(request, 'forum/detail.html', {'post': post})


def delete(request, pk):
    post = Post.objects.get(pk=pk)
    post.delete()
    return redirect('/forum/')


def edit(request, pk):
    post = Post.objects.get(pk=pk)
    return render(request, 'forum/edit.html', {'post': post})


def update(request, pk):
    post = Post.objects.get(pk=pk)
    title = request.GET.get('title')
    body = request.GET.get('content')

    post.title = title
    post.body = body

    post = Post(title=title, body=body)
    post.save()

    return redirect('/forum/')

post/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Post
from .forms import PostForm
from django.http import HttpResponse


def article(request):
    posts = Post.objects.all()
    return render(request, 'post/article.html', {'posts': posts})


def new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('/post/')
    else:
        form = PostForm()
    context = {'form': form}
    return render(request, 'post/new.html', context)


def detail(request, pk):
    post = Post.objects.get(pk=pk)
    return render(request, 'post/detail.html', {'post': post})


def delete(request, pk):
    post = Post.objects.get(pk=pk)
    post.delete()
    return redirect('/post/')


def edit(request, pk):
    post = Post.objects.get(pk=pk)
    return render(request, 'post/edit.html', {'post': post})


def update(request, pk):
    post = Post.objects.get(pk=pk)
    title = request.GET.get('title')
    body = request.GET.get('content')

    post.title = title
    post.body = body

    post = Post(title=title, body=body)
    post.save()

    return redirect('/post/')

templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
    <div class="container my-3">
        <form method="post" action="{% url 'accounts:login' %}">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="mb-3">
                <label for="username">사용자 ID</label>
                <input type="text" class="form-control" name="username" id="username"
                       value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password">비밀번호</label>
                <input type="password" class="form-control" name="password" id="password"
                       value="{{ form.password.value|default_if_none:'' }}">
            </div>
            <button type="submit" class="btn btn-dark">로그인</button>
        </form>
    </div>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
    <h2>여기는 유저 프로필 페이지입니다. </h2>
    {{ get_user.email }}
    {{ get_user.id }}

    {% if user.id == get_user.id %}
        <a href="{% url 'accounts:profile_change' %}" class="btn btn-dark">프로필 수정</a>
    {% endif %}
{% endblock %}

templates/accounts/profile_change.html
{% extends "base.html" %}
{% block content %}
    프로필 변경 페이지입니다.

    <a href="{% url 'accounts:pw_change' %}" class="btn btn-dark">비밀번호 변경</a>
{% endblock %}

templates/accounts/pw_change.html
{% extends "base.html" %}
{% block content %}
    비밀번호 변경 페이지입니다.
{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %}
{% block content %}
    <div class="container my-3">
        <form method="post" action="{% url 'accounts:signup' %}">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="mb-3">
                <label for="username">닉네임</label>
                <input type="text" class="form-control" name="username" id="username"
                       value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="first_name">(선택) 이름</label>
                <input type="text" class="form-control" name="first_name" id="first_name"
                       value="{{ form.first_name.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="last_name">(선택) 성</label>
                <input type="text" class="form-control" name="last_name" id="last_name"
                       value="{{ form.last_name.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password1">비밀번호</label>
                <input type="password" class="form-control" name="password1" id="password1"
                       value="{{ form.password1.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password2">비밀번호 확인</label>
                <input type="password" class="form-control" name="password2" id="password2"
                       value="{{ form.password2.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="email">이메일</label>
                <input type="text" class="form-control" name="email" id="email"
                       value="{{ form.email.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <button type="submit" class="btn btn-dark">생성하기</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, world!</title>
</head>
<body>
<!-- 네비게이션 바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
    <div class="alert alert-danger">
        {% for field in form %}
            <!-- 필드 오류 -->
            {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
            {% endif %}
        {% endfor %}
        <!-- 넌필드 오류 -->
        {% for error in form.non_field_errors %}
            <div>
                <strong>{{ error }}</strong>
            </div>
        {% endfor %}
    </div>
{% endif %}

templates/forum/article.html
{% extends 'base.html' %}

{% block content %}
<h2>게시판</h2>
<a href='/forum/new/'>New</a>
        {%  for post in posts %}
        <h2>제목 : {{ post.title }}</h2>
        <h2>내용 : {{ post.body }}</h2>
            <a href='{{ post.pk }}/'>DETAIL</a>
    {% endfor %}
{% endblock %}

templates/forum/detail.html
{% extends 'base.html' %}

{% block content %}
<h2>Detail</h2>
    <p>글 번호 : {{ post.id }}</p>
    <h1>제목 : {{ post.title }}</h1>
    <p>내용 : {{ post.body }}</p>
    <p>작성일자 : {{ post.created_at }}</p>
    <a href="/forum/{{ post.pk }}/delete/">Delete</a>
    <br>
    <a href="/forum">Back</a>
{% endblock %}

templates/forum/edit.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
</form>
{% endblock %}

templates/forum/home.html
{% extends "base.html" %}
{% block content %}
    <body>
    <div class="container my-3">
        사이트 홈 화면입니다.
    </div>
    </body>
{% endblock %}

templates/forum/new.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
{% endblock %}

templates/navbar.html
<!-- 네비게이션 바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-1g-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'site_home' %}">홈</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'forum:home' %}">포럼</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:get_member' %}">{{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    {% if not user.is_authenticated %}
                        <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>